# Generated by Django 4.2.27 on 2025-12-03 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('brand_logo', models.TextField(blank=True)),
                ('domain_url', models.URLField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('cta_style', models.CharField(choices=[('cart', 'Add to Cart'), ('bag', 'Add to Bag')], default='cart', max_length=10)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_message', models.TextField(blank=True)),
                ('catalogue_template', models.CharField(choices=[('minimal', 'Minimal'), ('elegant', 'Elegant'), ('bold', 'Bold'), ('compact', 'Compact')], default='minimal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('owner', 'sku'), name='unique_sku_per_owner'),
        ),
    ]
