# Generated by Django 4.2.27 on 2025-12-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
