# Generated by Django 4.2.27 on 2025-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_storesettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='domain_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
